### ISSUE TITLE
Some chat messages in a row are shown multiple times

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#555] opened 2016-10-26 15:30 UTC
@julianseeger and I spoke about chat UI and observed this by accident. He can provide a screenshot.

**Comment by thechauffeur** [comment] 2016-10-26 15:31
Maybe related to #554 (occurrence of these bugs may correlate).

**Comment by julianseeger** [comment] 2016-10-27 07:39
Seems like I fixed that in https://github.com/Qabel/qabel-desktop/pull/537/files#diff-57b0be378ac499de06c3d0b829029ddaL251
With the new UI it was easy to see / reproduce. It was a race condition because on every new message, the whole chat (ALL messages) got reloaded and that was not mutexed but happened in certain circumstances multiple times at one .. thus, some messages appeared multiple times, others were cleared and never showed up...

Now, the new messages are just appended to the existing message flow and that works perfectly fine.
=> should be fixed once https://github.com/Qabel/qabel-desktop/pull/537 is merged

**Closed** 2016-10-31 09:22 UTC
Labels: bug
