### ISSUE TITLE
Search & Import Contact from Index Server

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#412] opened 2016-08-22 13:22 UTC
```GHERKIN
As a Qabel Desktop User
In order to write messages to people whose email-address or phonenumber I know
I need to be able to search and import users from the qabel index server
```

In the mocks, we currently only have the menu entry:
![image](https://cloud.githubusercontent.com/assets/3258762/17855979/a6cef0d2-687b-11e6-85e9-a3209b684b0d.png)

//TBD with @thechauffeur for more details / scope

**Comment by mr-gosh** [comment] 2016-09-08 12:52
@julianseeger possible duplicate of #423 ?

**Comment by thechauffeur** [comment] 2016-09-08 15:05
The mockup missing label is correct because the UI component which is seen after clicking the "Search Qabel-Register-Service" button.

There must be an input field for the search for `telephone number` and/or `e-mail address`. Am I missing something @jmt85?

There must also be a mockup for the output and possibly selecting lists elements etc.

The search must work with the same input parameters and output forms as in Android.

**Comment by thechauffeur** [comment] 2016-09-08 15:05
#423 is a duplicate of this one.

**Comment by thechauffeur** [comment] 2016-09-08 15:06
As @julianseeger said in #423 ```The client code for the index server exists in the qabel core and new contacts get added via hello protocol, but there is no way to search and import new contacts from the index server.
This needs to be designed and added.```

**Comment by mr-gosh** [comment] 2016-09-09 09:51
I created a Qabel-Index-Import Wizard in three steps:
At first the Desktop Version (but the Android Version should look the same)

1.: open the search field and search for something:
![contacts-index_import-01](https://cloud.githubusercontent.com/assets/3028703/18382921/64f6bde6-7683-11e6-99ed-c781ef3553a5.png)

2.: select the desired contacts:
![contacts-index_import-02](https://cloud.githubusercontent.com/assets/3028703/18382960/8d887006-7683-11e6-9a73-a9fd777f2ec4.png)

3.: assign identities to the contacts and finish the wizard>
![contacts-index_import-03](https://cloud.githubusercontent.com/assets/3028703/18383009/c7e71766-7683-11e6-9260-06495a75d98c.png)

**Comment by mr-gosh** [comment] 2016-09-09 09:52
@thechauffeur self explaining enough?

**Comment by enkore** [comment] 2016-09-09 10:35
There's no "last modified" on these, but it can be added if need be.

**Comment by julianseeger** [comment] 2016-09-11 08:03
Maybe the explanation get's less complex if we provide two Fields (phone / email) with full validation. To let the user know he can only search for full mail addresses and not prefixes or suffixes ... or for full phone numbers where we could show the user the required format (like not spaces, no "-", no whatever and the format of the language code, maybe as a chooser. Just an idea but it sounds hard to describe to the user what exactly he has to insert if he only has one big input field and probably doesn't read the tooltip at all

**Comment by audax** [comment] 2016-09-12 08:55
Yes, what @julianseeger said.

**Comment by enkore** [comment] 2016-09-12 09:55
For the phone number field any non-numericals can just be removed. If the phone number entered doesn't have a country code (+49...) either a small hint should be shown or maybe just the CC of the current locale be added (e.g. I enter `089 1234567` and that gets converted to `+490891234567`). But maybe _stay out of that literal minefield of complexity_ entirely and just put a hint there.

**Comment by JoGir** [comment] 2016-09-12 14:09
we can normalize phonenumbers with PhoneNumberUtils (https://github.com/googlei18n/libphonenumber) to E.164 (http://www.itwissen.info/definition/lexikon/E-164-E-164.html)

**Closed** 2016-09-23 23:21 UTC
