### ISSUE TITLE
Index-Server: Suche & Import

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#423] opened 2016-09-05 09:25 UTC
The client code for the index server exists in the qabel core and new contacts get added via hello protocol, but there is no way to search and import new contacts from the index server.
This needs to be designed and added.

@jmt85 enhancement / feature?

**Comment by jmt85** [comment] 2016-09-05 09:31
everything fine

**Comment by thechauffeur** [comment] 2016-09-08 15:06
duplicate of #412

**Closed by thechauffeur** 2016-09-08 15:06 UTC
Labels: duplicate, enhancement, mockup missing
